### PR TITLE
Update packaged golang version to 1.19.1

### PR DESCRIPTION
**Pull request by ashmeer7**
This change updates the packaged golang version from 1.16 to 1.19.1. 1.16 has multiple known vulnerabilities which trips up vulnerability scanners. Updating to the latest golang version that is available at https://hub.docker.com/_/golang.

Once this is merged, I intend to upgrade the durable-task plugin with the new version.

Replaces https://github.com/jenkinsci/lib-durable-task/pull/59

- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira
- [x] Link to relevant pull requests, esp. upstream and downstream changes
- [x] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Comment by ashmeer7** [comment]
I currently don't know of a great way to add the test - If the plugin still builds, is that sufficient?

**Comment by ashmeer7** [comment]
Filed this ticket in case it helps: https://issues.jenkins.io/browse/JENKINS-69776

**Comment by car-roll** [comment]
Hi @ashmeer7 thanks for the PR!
Yes, there are some tests that run in the docker build process you can see here: https://ci.jenkins.io/blue/rest/organizations/jenkins/pipelines/jenkinsci-libraries/pipelines/lib-durable-task/branches/PR-60/runs/1/nodes/33/log/?start=0

The next step would actually be testing the [incrementals generated here](https://repo.jenkins-ci.org/incrementals/io/jenkins/plugins/lib-durable-task/35.v3d70a_4dd5860/) within the `durable-task` repo to make sure that all those tests have passed

**Comment by car-roll** [comment]
https://github.com/jenkinsci/durable-task-plugin/pull/154

**Review by car-roll — CHANGES_REQUESTED** [review]
We would also need to bump golang in the windows versions as well
https://github.com/jenkinsci/lib-durable-task/blob/main/src/Dockerfile.windows

**Comment by ashmeer7** [comment]
Just did the update, ill have a follow up PR as soon as the incremental version builds.

**Comment by ashmeer7** [comment]
Downstream test: https://github.com/jenkinsci/durable-task-plugin/pull/155

**Comment by ashmeer7** [comment]
Looks like the tests passed. Is there anything else we need to look into?

**Review by car-roll — APPROVED** [review]

**Review by car-roll — APPROVED** [review]
LGTM, thanks!

**Comment by ashmeer7** [comment]
@car-roll  - Does this need to be released? Or can I just send this version down?

**Comment by car-roll** [comment]
@ashmeer7 it needs a release. I'm in the process of starting one.

**Comment by car-roll** [comment]
https://github.com/jenkinsci/lib-durable-task/releases/tag/35.v59c17a_7e68b_f

**Comment by car-roll** [comment]
@ashmeer7 actually, feel free to update https://github.com/jenkinsci/durable-task-plugin/pull/155 with this version

**Pull request merged**
